### ISSUE TITLE
화면 좁아졌을때 목차 sticky 해제

### ISSUE THREAD

**Issue by GangHub1970** [Step3-kakao-tech-campus/Team8_FE#80]
# 🚨버그 리포트

## 어떤 버그인가요?

화면이 좁아졌을 때 목차가 sticky 속성때문에 내용을 가리는 버그

<br>

**Comment by qwer15948** [comment]
이거 저도 불편했어요
화면 좁아졌을 때 레이아웃 다시 잡아야할듯...!! 목차를 사이드에 꺼내고 닫는 형식으로 바꾸던가?

**Comment by GangHub1970** [comment]
앗 댓글을 수정하고 나서 봤네요.. 일단 지금은 그냥 좁아지면 sticky 속성 없애고 위로 스크롤돼서 사라지게 해놨어요!
